[package]
name = "xtask"
version = "4.4.1"
edition = "2024"

[dependencies]
log = "0.4.28"
strum = "0.27.2"

tracel-xtask = { version = "=5.0.0", features = ["build", "bump", "check", "fix", "infra", "test"] }
# ### For local development. ###
# tracel-xtask = { path = "../../xtask/crates/tracel-xtask", default-features = false }
