[package]
name = "provider-grafana-grafana"
version = "4.47.0"
edition = "2024"
description = "Grafana Terraform Provider bindings for terrars"
readme = "README.md"
license = "ISC"
repository = "https://github.com/tracel-ai/tracel-terrars/crates/provider-grafana-grafana"

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.terrars]
workspace = true

[features]
cloud_access_policy = []
cloud_access_policy_token = []
contact_point = []
dashboard = []
data_cloud_stack = []
data_source = []
fleet_management_pipeline = []
folder = []
playlist = []
rule_group = []
