use super::provider::ProviderGoogle;
use serde::Serialize;
use std::cell::RefCell;
use std::rc::Rc;
use terrars::*;
#[derive(Serialize)]
struct DataBackupDrBackupPlanData {
    #[serde(skip_serializing_if = "Vec::is_empty")]
    depends_on: Vec<String>,
    #[serde(skip_serializing_if = "SerdeSkipDefault::is_default")]
    provider: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    for_each: Option<String>,
    backup_plan_id: PrimField<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    id: Option<PrimField<String>>,
    location: PrimField<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    project: Option<PrimField<String>>,
}
struct DataBackupDrBackupPlan_ {
    shared: StackShared,
    tf_id: String,
    data: RefCell<DataBackupDrBackupPlanData>,
}
#[derive(Clone)]
pub struct DataBackupDrBackupPlan(Rc<DataBackupDrBackupPlan_>);
impl DataBackupDrBackupPlan {
    fn shared(&self) -> &StackShared {
        &self.0.shared
    }
    pub fn depends_on(self, dep: &impl Referable) -> Self {
        self.0.data.borrow_mut().depends_on.push(dep.extract_ref());
        self
    }
    pub fn set_provider(&self, provider: &ProviderGoogle) -> &Self {
        self.0.data.borrow_mut().provider = Some(provider.provider_ref());
        self
    }
    #[doc = "Set the field `id`.\n"]
    pub fn set_id(self, v: impl Into<PrimField<String>>) -> Self {
        self.0.data.borrow_mut().id = Some(v.into());
        self
    }
    #[doc = "Set the field `project`.\n"]
    pub fn set_project(self, v: impl Into<PrimField<String>>) -> Self {
        self.0.data.borrow_mut().project = Some(v.into());
        self
    }
    #[doc = "Get a reference to the value of field `backup_plan_id` after provisioning.\nThe ID of the backup plan"]
    pub fn backup_plan_id(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.backup_plan_id", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `backup_rules` after provisioning.\nThe backup rules for this 'BackupPlan'."]
    pub fn backup_rules(&self) -> ListRef<DataBackupDrBackupPlanBackupRulesElRef> {
        ListRef::new(
            self.shared().clone(),
            format!("{}.backup_rules", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `backup_vault` after provisioning.\nBackup vault where the backups gets stored using this Backup plan."]
    pub fn backup_vault(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.backup_vault", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `backup_vault_service_account` after provisioning.\nThe Google Cloud Platform Service Account to be used by the BackupVault for taking backups."]
    pub fn backup_vault_service_account(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.backup_vault_service_account", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `compute_instance_backup_plan_properties` after provisioning.\nDefines optional compute instance related properties for backups generated by this plan."]
    pub fn compute_instance_backup_plan_properties(
        &self,
    ) -> ListRef<DataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesElRef> {
        ListRef::new(
            self.shared().clone(),
            format!(
                "{}.compute_instance_backup_plan_properties",
                self.extract_ref()
            ),
        )
    }
    #[doc = "Get a reference to the value of field `create_time` after provisioning.\nWhen the 'BackupPlan' was created."]
    pub fn create_time(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.create_time", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `deletion_policy` after provisioning.\nWhether Terraform will be prevented from destroying the instance. Defaults to \"DELETE\".\nWhen a 'terraform destroy' or 'terraform apply' would delete the instance,\nthe command will fail if this field is set to \"PREVENT\" in Terraform state.\nWhen set to \"ABANDON\", the command will remove the resource from Terraform\nmanagement without updating or deleting the resource in the API.\nWhen set to \"DELETE\", deleting the resource is allowed.\n"]
    pub fn deletion_policy(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.deletion_policy", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `description` after provisioning.\nThe description allows for additional details about 'BackupPlan' and its use cases to be provided."]
    pub fn description(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.description", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `disk_backup_plan_properties` after provisioning.\nDefines optional disk related properties for backups generated by this plan."]
    pub fn disk_backup_plan_properties(
        &self,
    ) -> ListRef<DataBackupDrBackupPlanDiskBackupPlanPropertiesElRef> {
        ListRef::new(
            self.shared().clone(),
            format!("{}.disk_backup_plan_properties", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `id` after provisioning.\n"]
    pub fn id(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.id", self.extract_ref()))
    }
    #[doc = "Get a reference to the value of field `location` after provisioning.\nThe location for the backup plan"]
    pub fn location(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.location", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `log_retention_days` after provisioning.\nThis is only applicable for CloudSql resource. Days for which logs will be stored. This value should be greater than or equal to minimum enforced log retention duration of the backup vault."]
    pub fn log_retention_days(&self) -> PrimExpr<f64> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.log_retention_days", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `max_custom_on_demand_retention_days` after provisioning.\nThe maximum number of days for which an on-demand backup taken with custom retention can be retained."]
    pub fn max_custom_on_demand_retention_days(&self) -> PrimExpr<f64> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.max_custom_on_demand_retention_days", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `name` after provisioning.\nThe name of backup plan resource created"]
    pub fn name(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.name", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `project` after provisioning.\n"]
    pub fn project(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.project", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `resource_type` after provisioning.\nThe resource type to which the 'BackupPlan' will be applied.\nExamples include, \"compute.googleapis.com/Instance\", \"compute.googleapis.com/Disk\", \"sqladmin.googleapis.com/Instance\", \"alloydb.googleapis.com/Cluster\", \"file.googleapis.com/Instance\" and \"storage.googleapis.com/Bucket\"."]
    pub fn resource_type(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.resource_type", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `supported_resource_types` after provisioning.\nThe list of all resource types to which the 'BackupPlan' can be applied."]
    pub fn supported_resource_types(&self) -> ListRef<PrimExpr<String>> {
        ListRef::new(
            self.shared().clone(),
            format!("{}.supported_resource_types", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `update_time` after provisioning.\nWhen the 'BackupPlan' was last updated."]
    pub fn update_time(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.update_time", self.extract_ref()),
        )
    }
}
impl Referable for DataBackupDrBackupPlan {
    fn extract_ref(&self) -> String {
        format!(
            "data.{}.{}",
            self.0.extract_datasource_type(),
            self.0.extract_tf_id()
        )
    }
}
impl Datasource for DataBackupDrBackupPlan {}
impl ToListMappable for DataBackupDrBackupPlan {
    type O = ListRef<DataBackupDrBackupPlanRef>;
    fn do_map(self, base: String) -> Self::O {
        self.0.data.borrow_mut().for_each = Some(format!("${{{}}}", base));
        ListRef::new(self.0.shared.clone(), self.extract_ref())
    }
}
impl Datasource_ for DataBackupDrBackupPlan_ {
    fn extract_datasource_type(&self) -> String {
        "google_backup_dr_backup_plan".into()
    }
    fn extract_tf_id(&self) -> String {
        self.tf_id.clone()
    }
    fn extract_value(&self) -> serde_json::Value {
        serde_json::to_value(&self.data).unwrap()
    }
}
pub struct BuildDataBackupDrBackupPlan {
    pub tf_id: String,
    #[doc = "The ID of the backup plan"]
    pub backup_plan_id: PrimField<String>,
    #[doc = "The location for the backup plan"]
    pub location: PrimField<String>,
}
impl BuildDataBackupDrBackupPlan {
    pub fn build(self, stack: &mut Stack) -> DataBackupDrBackupPlan {
        let out = DataBackupDrBackupPlan(Rc::new(DataBackupDrBackupPlan_ {
            shared: stack.shared.clone(),
            tf_id: self.tf_id,
            data: RefCell::new(DataBackupDrBackupPlanData {
                depends_on: core::default::Default::default(),
                provider: None,
                for_each: None,
                backup_plan_id: self.backup_plan_id,
                id: core::default::Default::default(),
                location: self.location,
                project: core::default::Default::default(),
            }),
        }));
        stack.add_datasource(out.0.clone());
        out
    }
}
pub struct DataBackupDrBackupPlanRef {
    shared: StackShared,
    base: String,
}
impl Ref for DataBackupDrBackupPlanRef {
    fn new(shared: StackShared, base: String) -> Self {
        Self { shared, base }
    }
}
impl DataBackupDrBackupPlanRef {
    fn shared(&self) -> &StackShared {
        &self.shared
    }
    fn extract_ref(&self) -> String {
        self.base.clone()
    }
    #[doc = "Get a reference to the value of field `backup_plan_id` after provisioning.\nThe ID of the backup plan"]
    pub fn backup_plan_id(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.backup_plan_id", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `backup_rules` after provisioning.\nThe backup rules for this 'BackupPlan'."]
    pub fn backup_rules(&self) -> ListRef<DataBackupDrBackupPlanBackupRulesElRef> {
        ListRef::new(
            self.shared().clone(),
            format!("{}.backup_rules", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `backup_vault` after provisioning.\nBackup vault where the backups gets stored using this Backup plan."]
    pub fn backup_vault(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.backup_vault", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `backup_vault_service_account` after provisioning.\nThe Google Cloud Platform Service Account to be used by the BackupVault for taking backups."]
    pub fn backup_vault_service_account(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.backup_vault_service_account", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `compute_instance_backup_plan_properties` after provisioning.\nDefines optional compute instance related properties for backups generated by this plan."]
    pub fn compute_instance_backup_plan_properties(
        &self,
    ) -> ListRef<DataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesElRef> {
        ListRef::new(
            self.shared().clone(),
            format!(
                "{}.compute_instance_backup_plan_properties",
                self.extract_ref()
            ),
        )
    }
    #[doc = "Get a reference to the value of field `create_time` after provisioning.\nWhen the 'BackupPlan' was created."]
    pub fn create_time(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.create_time", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `deletion_policy` after provisioning.\nWhether Terraform will be prevented from destroying the instance. Defaults to \"DELETE\".\nWhen a 'terraform destroy' or 'terraform apply' would delete the instance,\nthe command will fail if this field is set to \"PREVENT\" in Terraform state.\nWhen set to \"ABANDON\", the command will remove the resource from Terraform\nmanagement without updating or deleting the resource in the API.\nWhen set to \"DELETE\", deleting the resource is allowed.\n"]
    pub fn deletion_policy(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.deletion_policy", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `description` after provisioning.\nThe description allows for additional details about 'BackupPlan' and its use cases to be provided."]
    pub fn description(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.description", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `disk_backup_plan_properties` after provisioning.\nDefines optional disk related properties for backups generated by this plan."]
    pub fn disk_backup_plan_properties(
        &self,
    ) -> ListRef<DataBackupDrBackupPlanDiskBackupPlanPropertiesElRef> {
        ListRef::new(
            self.shared().clone(),
            format!("{}.disk_backup_plan_properties", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `id` after provisioning.\n"]
    pub fn id(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.id", self.extract_ref()))
    }
    #[doc = "Get a reference to the value of field `location` after provisioning.\nThe location for the backup plan"]
    pub fn location(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.location", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `log_retention_days` after provisioning.\nThis is only applicable for CloudSql resource. Days for which logs will be stored. This value should be greater than or equal to minimum enforced log retention duration of the backup vault."]
    pub fn log_retention_days(&self) -> PrimExpr<f64> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.log_retention_days", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `max_custom_on_demand_retention_days` after provisioning.\nThe maximum number of days for which an on-demand backup taken with custom retention can be retained."]
    pub fn max_custom_on_demand_retention_days(&self) -> PrimExpr<f64> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.max_custom_on_demand_retention_days", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `name` after provisioning.\nThe name of backup plan resource created"]
    pub fn name(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.name", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `project` after provisioning.\n"]
    pub fn project(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.project", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `resource_type` after provisioning.\nThe resource type to which the 'BackupPlan' will be applied.\nExamples include, \"compute.googleapis.com/Instance\", \"compute.googleapis.com/Disk\", \"sqladmin.googleapis.com/Instance\", \"alloydb.googleapis.com/Cluster\", \"file.googleapis.com/Instance\" and \"storage.googleapis.com/Bucket\"."]
    pub fn resource_type(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.resource_type", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `supported_resource_types` after provisioning.\nThe list of all resource types to which the 'BackupPlan' can be applied."]
    pub fn supported_resource_types(&self) -> ListRef<PrimExpr<String>> {
        ListRef::new(
            self.shared().clone(),
            format!("{}.supported_resource_types", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `update_time` after provisioning.\nWhen the 'BackupPlan' was last updated."]
    pub fn update_time(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.update_time", self.extract_ref()),
        )
    }
}
#[derive(Serialize)]
pub struct DataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowEl {
    #[serde(skip_serializing_if = "Option::is_none")]
    end_hour_of_day: Option<PrimField<f64>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    start_hour_of_day: Option<PrimField<f64>>,
}
impl DataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowEl {
    #[doc = "Set the field `end_hour_of_day`.\n"]
    pub fn set_end_hour_of_day(mut self, v: impl Into<PrimField<f64>>) -> Self {
        self.end_hour_of_day = Some(v.into());
        self
    }
    #[doc = "Set the field `start_hour_of_day`.\n"]
    pub fn set_start_hour_of_day(mut self, v: impl Into<PrimField<f64>>) -> Self {
        self.start_hour_of_day = Some(v.into());
        self
    }
}
impl ToListMappable for DataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowEl {
    type O = BlockAssignable<DataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowEl>;
    fn do_map(self, base: String) -> Self::O {
        BlockAssignable::Dynamic(DynamicBlock {
            for_each: format!("${{{}}}", base),
            iterator: "each".into(),
            content: self,
        })
    }
}
pub struct BuildDataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowEl {}
impl BuildDataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowEl {
    pub fn build(self) -> DataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowEl {
        DataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowEl {
            end_hour_of_day: core::default::Default::default(),
            start_hour_of_day: core::default::Default::default(),
        }
    }
}
pub struct DataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowElRef {
    shared: StackShared,
    base: String,
}
impl Ref for DataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowElRef {
    fn new(
        shared: StackShared,
        base: String,
    ) -> DataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowElRef {
        DataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowElRef {
            shared: shared,
            base: base.to_string(),
        }
    }
}
impl DataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowElRef {
    fn shared(&self) -> &StackShared {
        &self.shared
    }
    #[doc = "Get a reference to the value of field `end_hour_of_day` after provisioning.\n"]
    pub fn end_hour_of_day(&self) -> PrimExpr<f64> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.end_hour_of_day", self.base),
        )
    }
    #[doc = "Get a reference to the value of field `start_hour_of_day` after provisioning.\n"]
    pub fn start_hour_of_day(&self) -> PrimExpr<f64> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.start_hour_of_day", self.base),
        )
    }
}
#[derive(Serialize)]
pub struct DataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthEl {
    #[serde(skip_serializing_if = "Option::is_none")]
    day_of_week: Option<PrimField<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    week_of_month: Option<PrimField<String>>,
}
impl DataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthEl {
    #[doc = "Set the field `day_of_week`.\n"]
    pub fn set_day_of_week(mut self, v: impl Into<PrimField<String>>) -> Self {
        self.day_of_week = Some(v.into());
        self
    }
    #[doc = "Set the field `week_of_month`.\n"]
    pub fn set_week_of_month(mut self, v: impl Into<PrimField<String>>) -> Self {
        self.week_of_month = Some(v.into());
        self
    }
}
impl ToListMappable for DataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthEl {
    type O = BlockAssignable<DataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthEl>;
    fn do_map(self, base: String) -> Self::O {
        BlockAssignable::Dynamic(DynamicBlock {
            for_each: format!("${{{}}}", base),
            iterator: "each".into(),
            content: self,
        })
    }
}
pub struct BuildDataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthEl {}
impl BuildDataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthEl {
    pub fn build(self) -> DataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthEl {
        DataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthEl {
            day_of_week: core::default::Default::default(),
            week_of_month: core::default::Default::default(),
        }
    }
}
pub struct DataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthElRef {
    shared: StackShared,
    base: String,
}
impl Ref for DataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthElRef {
    fn new(
        shared: StackShared,
        base: String,
    ) -> DataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthElRef {
        DataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthElRef {
            shared: shared,
            base: base.to_string(),
        }
    }
}
impl DataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthElRef {
    fn shared(&self) -> &StackShared {
        &self.shared
    }
    #[doc = "Get a reference to the value of field `day_of_week` after provisioning.\n"]
    pub fn day_of_week(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.day_of_week", self.base))
    }
    #[doc = "Get a reference to the value of field `week_of_month` after provisioning.\n"]
    pub fn week_of_month(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.week_of_month", self.base),
        )
    }
}
#[derive(Serialize)]
pub struct DataBackupDrBackupPlanBackupRulesElStandardScheduleEl {
    #[serde(skip_serializing_if = "Option::is_none")]
    backup_window:
        Option<ListField<DataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowEl>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    days_of_month: Option<ListField<PrimField<f64>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    days_of_week: Option<ListField<PrimField<String>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    hourly_frequency: Option<PrimField<f64>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    months: Option<ListField<PrimField<String>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    recurrence_type: Option<PrimField<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    time_zone: Option<PrimField<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    week_day_of_month:
        Option<ListField<DataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthEl>>,
}
impl DataBackupDrBackupPlanBackupRulesElStandardScheduleEl {
    #[doc = "Set the field `backup_window`.\n"]
    pub fn set_backup_window(
        mut self,
        v: impl Into<ListField<DataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowEl>>,
    ) -> Self {
        self.backup_window = Some(v.into());
        self
    }
    #[doc = "Set the field `days_of_month`.\n"]
    pub fn set_days_of_month(mut self, v: impl Into<ListField<PrimField<f64>>>) -> Self {
        self.days_of_month = Some(v.into());
        self
    }
    #[doc = "Set the field `days_of_week`.\n"]
    pub fn set_days_of_week(mut self, v: impl Into<ListField<PrimField<String>>>) -> Self {
        self.days_of_week = Some(v.into());
        self
    }
    #[doc = "Set the field `hourly_frequency`.\n"]
    pub fn set_hourly_frequency(mut self, v: impl Into<PrimField<f64>>) -> Self {
        self.hourly_frequency = Some(v.into());
        self
    }
    #[doc = "Set the field `months`.\n"]
    pub fn set_months(mut self, v: impl Into<ListField<PrimField<String>>>) -> Self {
        self.months = Some(v.into());
        self
    }
    #[doc = "Set the field `recurrence_type`.\n"]
    pub fn set_recurrence_type(mut self, v: impl Into<PrimField<String>>) -> Self {
        self.recurrence_type = Some(v.into());
        self
    }
    #[doc = "Set the field `time_zone`.\n"]
    pub fn set_time_zone(mut self, v: impl Into<PrimField<String>>) -> Self {
        self.time_zone = Some(v.into());
        self
    }
    #[doc = "Set the field `week_day_of_month`.\n"]
    pub fn set_week_day_of_month(
        mut self,
        v: impl Into<ListField<DataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthEl>>,
    ) -> Self {
        self.week_day_of_month = Some(v.into());
        self
    }
}
impl ToListMappable for DataBackupDrBackupPlanBackupRulesElStandardScheduleEl {
    type O = BlockAssignable<DataBackupDrBackupPlanBackupRulesElStandardScheduleEl>;
    fn do_map(self, base: String) -> Self::O {
        BlockAssignable::Dynamic(DynamicBlock {
            for_each: format!("${{{}}}", base),
            iterator: "each".into(),
            content: self,
        })
    }
}
pub struct BuildDataBackupDrBackupPlanBackupRulesElStandardScheduleEl {}
impl BuildDataBackupDrBackupPlanBackupRulesElStandardScheduleEl {
    pub fn build(self) -> DataBackupDrBackupPlanBackupRulesElStandardScheduleEl {
        DataBackupDrBackupPlanBackupRulesElStandardScheduleEl {
            backup_window: core::default::Default::default(),
            days_of_month: core::default::Default::default(),
            days_of_week: core::default::Default::default(),
            hourly_frequency: core::default::Default::default(),
            months: core::default::Default::default(),
            recurrence_type: core::default::Default::default(),
            time_zone: core::default::Default::default(),
            week_day_of_month: core::default::Default::default(),
        }
    }
}
pub struct DataBackupDrBackupPlanBackupRulesElStandardScheduleElRef {
    shared: StackShared,
    base: String,
}
impl Ref for DataBackupDrBackupPlanBackupRulesElStandardScheduleElRef {
    fn new(
        shared: StackShared,
        base: String,
    ) -> DataBackupDrBackupPlanBackupRulesElStandardScheduleElRef {
        DataBackupDrBackupPlanBackupRulesElStandardScheduleElRef {
            shared: shared,
            base: base.to_string(),
        }
    }
}
impl DataBackupDrBackupPlanBackupRulesElStandardScheduleElRef {
    fn shared(&self) -> &StackShared {
        &self.shared
    }
    #[doc = "Get a reference to the value of field `backup_window` after provisioning.\n"]
    pub fn backup_window(
        &self,
    ) -> ListRef<DataBackupDrBackupPlanBackupRulesElStandardScheduleElBackupWindowElRef> {
        ListRef::new(
            self.shared().clone(),
            format!("{}.backup_window", self.base),
        )
    }
    #[doc = "Get a reference to the value of field `days_of_month` after provisioning.\n"]
    pub fn days_of_month(&self) -> ListRef<PrimExpr<f64>> {
        ListRef::new(
            self.shared().clone(),
            format!("{}.days_of_month", self.base),
        )
    }
    #[doc = "Get a reference to the value of field `days_of_week` after provisioning.\n"]
    pub fn days_of_week(&self) -> ListRef<PrimExpr<String>> {
        ListRef::new(self.shared().clone(), format!("{}.days_of_week", self.base))
    }
    #[doc = "Get a reference to the value of field `hourly_frequency` after provisioning.\n"]
    pub fn hourly_frequency(&self) -> PrimExpr<f64> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.hourly_frequency", self.base),
        )
    }
    #[doc = "Get a reference to the value of field `months` after provisioning.\n"]
    pub fn months(&self) -> ListRef<PrimExpr<String>> {
        ListRef::new(self.shared().clone(), format!("{}.months", self.base))
    }
    #[doc = "Get a reference to the value of field `recurrence_type` after provisioning.\n"]
    pub fn recurrence_type(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.recurrence_type", self.base),
        )
    }
    #[doc = "Get a reference to the value of field `time_zone` after provisioning.\n"]
    pub fn time_zone(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.time_zone", self.base))
    }
    #[doc = "Get a reference to the value of field `week_day_of_month` after provisioning.\n"]
    pub fn week_day_of_month(
        &self,
    ) -> ListRef<DataBackupDrBackupPlanBackupRulesElStandardScheduleElWeekDayOfMonthElRef> {
        ListRef::new(
            self.shared().clone(),
            format!("{}.week_day_of_month", self.base),
        )
    }
}
#[derive(Serialize)]
pub struct DataBackupDrBackupPlanBackupRulesEl {
    #[serde(skip_serializing_if = "Option::is_none")]
    backup_retention_days: Option<PrimField<f64>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    rule_id: Option<PrimField<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    standard_schedule: Option<ListField<DataBackupDrBackupPlanBackupRulesElStandardScheduleEl>>,
}
impl DataBackupDrBackupPlanBackupRulesEl {
    #[doc = "Set the field `backup_retention_days`.\n"]
    pub fn set_backup_retention_days(mut self, v: impl Into<PrimField<f64>>) -> Self {
        self.backup_retention_days = Some(v.into());
        self
    }
    #[doc = "Set the field `rule_id`.\n"]
    pub fn set_rule_id(mut self, v: impl Into<PrimField<String>>) -> Self {
        self.rule_id = Some(v.into());
        self
    }
    #[doc = "Set the field `standard_schedule`.\n"]
    pub fn set_standard_schedule(
        mut self,
        v: impl Into<ListField<DataBackupDrBackupPlanBackupRulesElStandardScheduleEl>>,
    ) -> Self {
        self.standard_schedule = Some(v.into());
        self
    }
}
impl ToListMappable for DataBackupDrBackupPlanBackupRulesEl {
    type O = BlockAssignable<DataBackupDrBackupPlanBackupRulesEl>;
    fn do_map(self, base: String) -> Self::O {
        BlockAssignable::Dynamic(DynamicBlock {
            for_each: format!("${{{}}}", base),
            iterator: "each".into(),
            content: self,
        })
    }
}
pub struct BuildDataBackupDrBackupPlanBackupRulesEl {}
impl BuildDataBackupDrBackupPlanBackupRulesEl {
    pub fn build(self) -> DataBackupDrBackupPlanBackupRulesEl {
        DataBackupDrBackupPlanBackupRulesEl {
            backup_retention_days: core::default::Default::default(),
            rule_id: core::default::Default::default(),
            standard_schedule: core::default::Default::default(),
        }
    }
}
pub struct DataBackupDrBackupPlanBackupRulesElRef {
    shared: StackShared,
    base: String,
}
impl Ref for DataBackupDrBackupPlanBackupRulesElRef {
    fn new(shared: StackShared, base: String) -> DataBackupDrBackupPlanBackupRulesElRef {
        DataBackupDrBackupPlanBackupRulesElRef {
            shared: shared,
            base: base.to_string(),
        }
    }
}
impl DataBackupDrBackupPlanBackupRulesElRef {
    fn shared(&self) -> &StackShared {
        &self.shared
    }
    #[doc = "Get a reference to the value of field `backup_retention_days` after provisioning.\n"]
    pub fn backup_retention_days(&self) -> PrimExpr<f64> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.backup_retention_days", self.base),
        )
    }
    #[doc = "Get a reference to the value of field `rule_id` after provisioning.\n"]
    pub fn rule_id(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.rule_id", self.base))
    }
    #[doc = "Get a reference to the value of field `standard_schedule` after provisioning.\n"]
    pub fn standard_schedule(
        &self,
    ) -> ListRef<DataBackupDrBackupPlanBackupRulesElStandardScheduleElRef> {
        ListRef::new(
            self.shared().clone(),
            format!("{}.standard_schedule", self.base),
        )
    }
}
#[derive(Serialize)]
pub struct DataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesEl {
    #[serde(skip_serializing_if = "Option::is_none")]
    guest_flush: Option<PrimField<bool>>,
}
impl DataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesEl {
    #[doc = "Set the field `guest_flush`.\n"]
    pub fn set_guest_flush(mut self, v: impl Into<PrimField<bool>>) -> Self {
        self.guest_flush = Some(v.into());
        self
    }
}
impl ToListMappable for DataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesEl {
    type O = BlockAssignable<DataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesEl>;
    fn do_map(self, base: String) -> Self::O {
        BlockAssignable::Dynamic(DynamicBlock {
            for_each: format!("${{{}}}", base),
            iterator: "each".into(),
            content: self,
        })
    }
}
pub struct BuildDataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesEl {}
impl BuildDataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesEl {
    pub fn build(self) -> DataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesEl {
        DataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesEl {
            guest_flush: core::default::Default::default(),
        }
    }
}
pub struct DataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesElRef {
    shared: StackShared,
    base: String,
}
impl Ref for DataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesElRef {
    fn new(
        shared: StackShared,
        base: String,
    ) -> DataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesElRef {
        DataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesElRef {
            shared: shared,
            base: base.to_string(),
        }
    }
}
impl DataBackupDrBackupPlanComputeInstanceBackupPlanPropertiesElRef {
    fn shared(&self) -> &StackShared {
        &self.shared
    }
    #[doc = "Get a reference to the value of field `guest_flush` after provisioning.\n"]
    pub fn guest_flush(&self) -> PrimExpr<bool> {
        PrimExpr::new(self.shared().clone(), format!("{}.guest_flush", self.base))
    }
}
#[derive(Serialize)]
pub struct DataBackupDrBackupPlanDiskBackupPlanPropertiesEl {
    #[serde(skip_serializing_if = "Option::is_none")]
    guest_flush: Option<PrimField<bool>>,
}
impl DataBackupDrBackupPlanDiskBackupPlanPropertiesEl {
    #[doc = "Set the field `guest_flush`.\n"]
    pub fn set_guest_flush(mut self, v: impl Into<PrimField<bool>>) -> Self {
        self.guest_flush = Some(v.into());
        self
    }
}
impl ToListMappable for DataBackupDrBackupPlanDiskBackupPlanPropertiesEl {
    type O = BlockAssignable<DataBackupDrBackupPlanDiskBackupPlanPropertiesEl>;
    fn do_map(self, base: String) -> Self::O {
        BlockAssignable::Dynamic(DynamicBlock {
            for_each: format!("${{{}}}", base),
            iterator: "each".into(),
            content: self,
        })
    }
}
pub struct BuildDataBackupDrBackupPlanDiskBackupPlanPropertiesEl {}
impl BuildDataBackupDrBackupPlanDiskBackupPlanPropertiesEl {
    pub fn build(self) -> DataBackupDrBackupPlanDiskBackupPlanPropertiesEl {
        DataBackupDrBackupPlanDiskBackupPlanPropertiesEl {
            guest_flush: core::default::Default::default(),
        }
    }
}
pub struct DataBackupDrBackupPlanDiskBackupPlanPropertiesElRef {
    shared: StackShared,
    base: String,
}
impl Ref for DataBackupDrBackupPlanDiskBackupPlanPropertiesElRef {
    fn new(
        shared: StackShared,
        base: String,
    ) -> DataBackupDrBackupPlanDiskBackupPlanPropertiesElRef {
        DataBackupDrBackupPlanDiskBackupPlanPropertiesElRef {
            shared: shared,
            base: base.to_string(),
        }
    }
}
impl DataBackupDrBackupPlanDiskBackupPlanPropertiesElRef {
    fn shared(&self) -> &StackShared {
        &self.shared
    }
    #[doc = "Get a reference to the value of field `guest_flush` after provisioning.\n"]
    pub fn guest_flush(&self) -> PrimExpr<bool> {
        PrimExpr::new(self.shared().clone(), format!("{}.guest_flush", self.base))
    }
}
