use super::provider::ProviderGoogle;
use serde::Serialize;
use std::cell::RefCell;
use std::rc::Rc;
use terrars::*;
#[derive(Serialize)]
struct WorkloadIdentityServiceAgentData {
    #[serde(skip_serializing_if = "Vec::is_empty")]
    depends_on: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    provider: Option<String>,
    #[serde(skip_serializing_if = "SerdeSkipDefault::is_default")]
    lifecycle: ResourceLifecycle,
    #[serde(skip_serializing_if = "Option::is_none")]
    for_each: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    id: Option<PrimField<String>>,
    parent: PrimField<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    timeouts: Option<WorkloadIdentityServiceAgentTimeoutsEl>,
}
struct WorkloadIdentityServiceAgent_ {
    shared: StackShared,
    tf_id: String,
    data: RefCell<WorkloadIdentityServiceAgentData>,
}
#[derive(Clone)]
pub struct WorkloadIdentityServiceAgent(Rc<WorkloadIdentityServiceAgent_>);
impl WorkloadIdentityServiceAgent {
    fn shared(&self) -> &StackShared {
        &self.0.shared
    }
    pub fn depends_on(self, dep: &impl Referable) -> Self {
        self.0.data.borrow_mut().depends_on.push(dep.extract_ref());
        self
    }
    pub fn set_provider(self, provider: &ProviderGoogle) -> Self {
        self.0.data.borrow_mut().provider = Some(provider.provider_ref());
        self
    }
    pub fn set_create_before_destroy(self, v: bool) -> Self {
        self.0.data.borrow_mut().lifecycle.create_before_destroy = v;
        self
    }
    pub fn set_prevent_destroy(self, v: bool) -> Self {
        self.0.data.borrow_mut().lifecycle.prevent_destroy = v;
        self
    }
    pub fn ignore_changes_to_all(self) -> Self {
        self.0.data.borrow_mut().lifecycle.ignore_changes =
            Some(IgnoreChanges::All(IgnoreChangesAll::All));
        self
    }
    pub fn ignore_changes_to_attr(self, attr: impl ToString) -> Self {
        {
            let mut d = self.0.data.borrow_mut();
            if match &mut d.lifecycle.ignore_changes {
                Some(i) => match i {
                    IgnoreChanges::All(_) => true,
                    IgnoreChanges::Refs(r) => {
                        r.push(attr.to_string());
                        false
                    }
                },
                None => true,
            } {
                d.lifecycle.ignore_changes = Some(IgnoreChanges::Refs(vec![attr.to_string()]));
            }
        }
        self
    }
    pub fn replace_triggered_by_resource(self, r: &impl Resource) -> Self {
        self.0
            .data
            .borrow_mut()
            .lifecycle
            .replace_triggered_by
            .push(r.extract_ref());
        self
    }
    pub fn replace_triggered_by_attr(self, attr: impl ToString) -> Self {
        self.0
            .data
            .borrow_mut()
            .lifecycle
            .replace_triggered_by
            .push(attr.to_string());
        self
    }
    #[doc = "Set the field `id`.\n"]
    pub fn set_id(self, v: impl Into<PrimField<String>>) -> Self {
        self.0.data.borrow_mut().id = Some(v.into());
        self
    }
    #[doc = "Set the field `timeouts`.\n"]
    pub fn set_timeouts(self, v: impl Into<WorkloadIdentityServiceAgentTimeoutsEl>) -> Self {
        self.0.data.borrow_mut().timeouts = Some(v.into());
        self
    }
    #[doc = "Get a reference to the value of field `id` after provisioning.\n"]
    pub fn id(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.id", self.extract_ref()))
    }
    #[doc = "Get a reference to the value of field `parent` after provisioning.\nThe parent resource path."]
    pub fn parent(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.parent", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `service_agents` after provisioning.\nThe list of ServiceAgents generated by the API call."]
    pub fn service_agents(&self) -> ListRef<WorkloadIdentityServiceAgentServiceAgentsElRef> {
        ListRef::new(
            self.shared().clone(),
            format!("{}.service_agents", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `timeouts` after provisioning.\n"]
    pub fn timeouts(&self) -> WorkloadIdentityServiceAgentTimeoutsElRef {
        WorkloadIdentityServiceAgentTimeoutsElRef::new(
            self.shared().clone(),
            format!("{}.timeouts", self.extract_ref()),
        )
    }
}
impl Referable for WorkloadIdentityServiceAgent {
    fn extract_ref(&self) -> String {
        format!(
            "{}.{}",
            self.0.extract_resource_type(),
            self.0.extract_tf_id()
        )
    }
}
impl Resource for WorkloadIdentityServiceAgent {}
impl ToListMappable for WorkloadIdentityServiceAgent {
    type O = ListRef<WorkloadIdentityServiceAgentRef>;
    fn do_map(self, base: String) -> Self::O {
        self.0.data.borrow_mut().for_each = Some(format!("${{{}}}", base));
        ListRef::new(self.0.shared.clone(), self.extract_ref())
    }
}
impl Resource_ for WorkloadIdentityServiceAgent_ {
    fn extract_resource_type(&self) -> String {
        "google_workload_identity_service_agent".into()
    }
    fn extract_tf_id(&self) -> String {
        self.tf_id.clone()
    }
    fn extract_value(&self) -> serde_json::Value {
        serde_json::to_value(&self.data).unwrap()
    }
}
pub struct BuildWorkloadIdentityServiceAgent {
    pub tf_id: String,
    #[doc = "The parent resource path."]
    pub parent: PrimField<String>,
}
impl BuildWorkloadIdentityServiceAgent {
    pub fn build(self, stack: &mut Stack) -> WorkloadIdentityServiceAgent {
        let out = WorkloadIdentityServiceAgent(Rc::new(WorkloadIdentityServiceAgent_ {
            shared: stack.shared.clone(),
            tf_id: self.tf_id,
            data: RefCell::new(WorkloadIdentityServiceAgentData {
                depends_on: core::default::Default::default(),
                provider: None,
                lifecycle: core::default::Default::default(),
                for_each: None,
                id: core::default::Default::default(),
                parent: self.parent,
                timeouts: core::default::Default::default(),
            }),
        }));
        stack.add_resource(out.0.clone());
        out
    }
}
pub struct WorkloadIdentityServiceAgentRef {
    shared: StackShared,
    base: String,
}
impl Ref for WorkloadIdentityServiceAgentRef {
    fn new(shared: StackShared, base: String) -> Self {
        Self { shared, base }
    }
}
impl WorkloadIdentityServiceAgentRef {
    fn extract_ref(&self) -> String {
        self.base.clone()
    }
    fn shared(&self) -> &StackShared {
        &self.shared
    }
    #[doc = "Get a reference to the value of field `id` after provisioning.\n"]
    pub fn id(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.id", self.extract_ref()))
    }
    #[doc = "Get a reference to the value of field `parent` after provisioning.\nThe parent resource path."]
    pub fn parent(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.parent", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `service_agents` after provisioning.\nThe list of ServiceAgents generated by the API call."]
    pub fn service_agents(&self) -> ListRef<WorkloadIdentityServiceAgentServiceAgentsElRef> {
        ListRef::new(
            self.shared().clone(),
            format!("{}.service_agents", self.extract_ref()),
        )
    }
    #[doc = "Get a reference to the value of field `timeouts` after provisioning.\n"]
    pub fn timeouts(&self) -> WorkloadIdentityServiceAgentTimeoutsElRef {
        WorkloadIdentityServiceAgentTimeoutsElRef::new(
            self.shared().clone(),
            format!("{}.timeouts", self.extract_ref()),
        )
    }
}
#[derive(Serialize)]
pub struct WorkloadIdentityServiceAgentServiceAgentsEl {
    #[serde(skip_serializing_if = "Option::is_none")]
    container: Option<PrimField<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    name: Option<PrimField<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    principal: Option<PrimField<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    role: Option<PrimField<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    service_producer: Option<PrimField<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    state: Option<PrimField<String>>,
}
impl WorkloadIdentityServiceAgentServiceAgentsEl {
    #[doc = "Set the field `container`.\n"]
    pub fn set_container(mut self, v: impl Into<PrimField<String>>) -> Self {
        self.container = Some(v.into());
        self
    }
    #[doc = "Set the field `name`.\n"]
    pub fn set_name(mut self, v: impl Into<PrimField<String>>) -> Self {
        self.name = Some(v.into());
        self
    }
    #[doc = "Set the field `principal`.\n"]
    pub fn set_principal(mut self, v: impl Into<PrimField<String>>) -> Self {
        self.principal = Some(v.into());
        self
    }
    #[doc = "Set the field `role`.\n"]
    pub fn set_role(mut self, v: impl Into<PrimField<String>>) -> Self {
        self.role = Some(v.into());
        self
    }
    #[doc = "Set the field `service_producer`.\n"]
    pub fn set_service_producer(mut self, v: impl Into<PrimField<String>>) -> Self {
        self.service_producer = Some(v.into());
        self
    }
    #[doc = "Set the field `state`.\n"]
    pub fn set_state(mut self, v: impl Into<PrimField<String>>) -> Self {
        self.state = Some(v.into());
        self
    }
}
impl ToListMappable for WorkloadIdentityServiceAgentServiceAgentsEl {
    type O = BlockAssignable<WorkloadIdentityServiceAgentServiceAgentsEl>;
    fn do_map(self, base: String) -> Self::O {
        BlockAssignable::Dynamic(DynamicBlock {
            for_each: format!("${{{}}}", base),
            iterator: "each".into(),
            content: self,
        })
    }
}
pub struct BuildWorkloadIdentityServiceAgentServiceAgentsEl {}
impl BuildWorkloadIdentityServiceAgentServiceAgentsEl {
    pub fn build(self) -> WorkloadIdentityServiceAgentServiceAgentsEl {
        WorkloadIdentityServiceAgentServiceAgentsEl {
            container: core::default::Default::default(),
            name: core::default::Default::default(),
            principal: core::default::Default::default(),
            role: core::default::Default::default(),
            service_producer: core::default::Default::default(),
            state: core::default::Default::default(),
        }
    }
}
pub struct WorkloadIdentityServiceAgentServiceAgentsElRef {
    shared: StackShared,
    base: String,
}
impl Ref for WorkloadIdentityServiceAgentServiceAgentsElRef {
    fn new(shared: StackShared, base: String) -> WorkloadIdentityServiceAgentServiceAgentsElRef {
        WorkloadIdentityServiceAgentServiceAgentsElRef {
            shared: shared,
            base: base.to_string(),
        }
    }
}
impl WorkloadIdentityServiceAgentServiceAgentsElRef {
    fn shared(&self) -> &StackShared {
        &self.shared
    }
    #[doc = "Get a reference to the value of field `container` after provisioning.\n"]
    pub fn container(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.container", self.base))
    }
    #[doc = "Get a reference to the value of field `name` after provisioning.\n"]
    pub fn name(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.name", self.base))
    }
    #[doc = "Get a reference to the value of field `principal` after provisioning.\n"]
    pub fn principal(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.principal", self.base))
    }
    #[doc = "Get a reference to the value of field `role` after provisioning.\n"]
    pub fn role(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.role", self.base))
    }
    #[doc = "Get a reference to the value of field `service_producer` after provisioning.\n"]
    pub fn service_producer(&self) -> PrimExpr<String> {
        PrimExpr::new(
            self.shared().clone(),
            format!("{}.service_producer", self.base),
        )
    }
    #[doc = "Get a reference to the value of field `state` after provisioning.\n"]
    pub fn state(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.state", self.base))
    }
}
#[derive(Serialize)]
pub struct WorkloadIdentityServiceAgentTimeoutsEl {
    #[serde(skip_serializing_if = "Option::is_none")]
    create: Option<PrimField<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    delete: Option<PrimField<String>>,
}
impl WorkloadIdentityServiceAgentTimeoutsEl {
    #[doc = "Set the field `create`.\n"]
    pub fn set_create(mut self, v: impl Into<PrimField<String>>) -> Self {
        self.create = Some(v.into());
        self
    }
    #[doc = "Set the field `delete`.\n"]
    pub fn set_delete(mut self, v: impl Into<PrimField<String>>) -> Self {
        self.delete = Some(v.into());
        self
    }
}
impl ToListMappable for WorkloadIdentityServiceAgentTimeoutsEl {
    type O = BlockAssignable<WorkloadIdentityServiceAgentTimeoutsEl>;
    fn do_map(self, base: String) -> Self::O {
        BlockAssignable::Dynamic(DynamicBlock {
            for_each: format!("${{{}}}", base),
            iterator: "each".into(),
            content: self,
        })
    }
}
pub struct BuildWorkloadIdentityServiceAgentTimeoutsEl {}
impl BuildWorkloadIdentityServiceAgentTimeoutsEl {
    pub fn build(self) -> WorkloadIdentityServiceAgentTimeoutsEl {
        WorkloadIdentityServiceAgentTimeoutsEl {
            create: core::default::Default::default(),
            delete: core::default::Default::default(),
        }
    }
}
pub struct WorkloadIdentityServiceAgentTimeoutsElRef {
    shared: StackShared,
    base: String,
}
impl Ref for WorkloadIdentityServiceAgentTimeoutsElRef {
    fn new(shared: StackShared, base: String) -> WorkloadIdentityServiceAgentTimeoutsElRef {
        WorkloadIdentityServiceAgentTimeoutsElRef {
            shared: shared,
            base: base.to_string(),
        }
    }
}
impl WorkloadIdentityServiceAgentTimeoutsElRef {
    fn shared(&self) -> &StackShared {
        &self.shared
    }
    #[doc = "Get a reference to the value of field `create` after provisioning.\n"]
    pub fn create(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.create", self.base))
    }
    #[doc = "Get a reference to the value of field `delete` after provisioning.\n"]
    pub fn delete(&self) -> PrimExpr<String> {
        PrimExpr::new(self.shared().clone(), format!("{}.delete", self.base))
    }
}
